{% set name = "control" %}
{% set version = "0.9.0" %}
{% set sha256 = "34eeca077cf002a2f22a9334c8998ec5b3bcc0fdae2aac790a923cf8bc80245a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base <3.0  # [py27]
    - matplotlib-base  # [not py27]
    # NOTE : Once Slycot is available as a Windows conda package, update this.
    - slycot  # [unix]

test:
  imports:
    - control

about:
  home: http://python-control.sourceforge.net
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/python-control/python-control
  doc_url: http://python-control.readthedocs.org/
  summary: 'Python Control Systems Library'

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
