{% set python_min = '3.10' %}
{% set name = "control" %}
{% set version = "0.10.2" %}
{% set sha256 = "d0cf63f6cfb68a4c8e827c26c3744d129e9777fedc9a5d86ca4740548f23a98b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - slycot

test:
  requires:
    - python {{ python_min }}
  imports:
    - control

about:
  home: https://python-control.org
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/python-control/python-control
  doc_url: https://python-control.readthedocs.org/
  summary: 'Python Control Systems Library'

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - bnavigator
