{% set name = "control" %}
{% set version = "0.9.4" %}
{% set sha256 = "0fa57d2216b7ac4e9339c09eab6827660318a641779335864feee940bd19c9ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base
    - slycot

test:
  imports:
    - control

about:
  home: https://python-control.org
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/python-control/python-control
  doc_url: https://python-control.readthedocs.org/
  summary: 'Python Control Systems Library'

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - bnavigator
