appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LjQqUJLAzDhJpA3qemCmF4HQHNLWpP4+efRFOx3ITvIrTHDAvS1j7+rDDnfUzZKhUngRqL4KRjfv3mh9O3fbxj0ywCSqgxYAXmXWYruIVG2zfABqRJFxbZrDizXqFtQGNOFL1oqnqPhb8xOqx2BsDKF8EzJmawIJnb7pqc+PBOHXedGuVS8qiVt9WXctSxulLP6+t3DI9ak+WD1HNNwhJhEzJ+QzX6C/Q2KeE6PAtwwbx79e4k6kvioJavllnkpXVqn8/B98K9NSKW3KgJy0nFJXr7iUUhWCl53Te36bWoZpsUfcNVs7bD/nvToPHfoke/2C06Um9cALpBt/k8rdOa7OJtPlfjwEjF98mzUtLB+T57IaZxE1D2gswZevEq4e4pvW8tH5eXrJ51UpUskJoSldYVO4R4UidGAi64kymebK2/MJJaedcz8YMpLV/qGpvRZZjaFtCJsmsFIcNyKy+DNzHIaEYssQC+jcSB6OXAsH9tGLBmAhXdlkKKMNmdzjcNqHU39AyslZjWvbFC/00XgE04/n3+htc04l9zNBOefB8M0iJ8yHmPvij2oZ11CymAWEkIlqhbRxiQ3JjkHcQtBLr00XIkFNF1g8md0Al0mPbIl6NUmXJu1IftSmHF3hrZqR3hYxfpBMikGUxAbud8Prr2+LoRDk/720T3aMB7I=}
